name: Automated Domain Availability Checker

on:
  schedule:
    # Run every hour at minute 0
    - cron: '0 * * * *'
  
  # Allow manual triggering for testing
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  check-domains:
    name: Check Domain Availability
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          
      - name: Check domain availability
        env:
          WHOIS_API_KEY: ${{ secrets.WHOIS_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          # Run domain checking with error handling
          if ! vibe check-domains; then
            echo "Domain check failed with exit code $?"
            exit 1
          fi
          echo "Domain check completed successfully"
          
      - name: Notify on failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          # Send failure notification to Slack
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"🚨 Domain Tracker GitHub Action Failed\n\nThe automated domain availability check encountered an error.\n\nWorkflow: ${{ github.workflow }}\nRun ID: ${{ github.run_id }}\nRepository: ${{ github.repository }}\nTimestamp: $(date -u +\"%Y-%m-%d %H:%M:%S UTC\")\n\nPlease check the GitHub Actions logs for details."}' \
            $SLACK_WEBHOOK_URL || echo "Failed to send Slack notification" 